
export const enum CIDERROR {
    USER_EXISTS = "CID_ERR_USER_ALREADY_EXISTS_WITH_THIS_EMAIL",
    USER_NOT_FOUND = "CID_ERR_USER_NOT_FOUND_WITH_THIS_EMAIL",
    USER_CREATION_FAILED = "CID_ERR_USER_CREATION_FAILED",
    USER_UPDATE_FAILED = "CID_ERR_USER_UPDATE_FAILED"
}